name: ncu
on: [pull_request]
jobs:
  ncu:
      name: npm check updates
      runs-on: macOS-latest
      strategy:
        matrix:
          node_version: [12]
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Setup node ${{ matrix.node_version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node_version }}

        - name: Install and run ncu
          run: |
            npm install npm-check-updates
            npx ncu --jsonDeps 1>upgrade

        - name: Report PR comment
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            URL: ${{ github.event.pull_request.comments_url }}
          run: |
            curl -X POST \
                 -H "Authorization: token ${GITHUB_TOKEN}" \
                 -d '{"body": "$(cat upgrade)"}' \
                 ${URL}
