name: ncu
on: [pull_request]
jobs:
  ncu:
      name: npm check updates
      runs-on: macOS-latest
      strategy:
        matrix:
          node_version: [12]
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Setup node ${{ matrix.node_version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node_version }}
  
        - name: Install and run ncu
          run: |
            npm install npm-check-updates
            npx ncu