name: ncu
on:
  [push, pull_request]
jobs:
  ncu_report:
    runs-on: ubuntu-latest
    name: npm-check-updates report
    steps:
      - uses: actions/ncu-report-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pacakge-manager: 'yarn'